baseURL: "https://nicolassaint.github.io/"
publishDir: "docs"
relativeURLs: false
canonifyURLs: true
languageCode: en-us
title: Nicolas Saint
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    # - identifier: blog
    #   name: Blog
    #   url: /blog
    #   weight: 20
    # - identifier: projects
    #   name: Projects
    #   url: /projects
    #   weight: 30
    - identifier: education
      name: Education
      url: /education/
      weight: 35
    - identifier: experience
      name: Experience
      url: /experience/
      weight: 40
    - identifier: chat
      name: Chat
      url: /chat/
      weight: 50
    # - identifier: search
    #   name: Search
    #   url: /search
    #   weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Nicolas Saint"
    subtitle: Hi 👋 I’m Nicolas, a tech and open-source AI 🤗 enthusiast passionate about solving complex problems. As a Data Science intern at the [**Ministry of Economy and Finance**](https://www.economie.gouv.fr/), I’m developing robust, sovereign, and privacy-focused AI tools (chatbots, RAG systems, summarization tools...) for the French government using state-of-the-art open-source models.


    imageUrl: "home/nicolassaint-london.jpg"
    imageWidth: 220
    imageHeight: 220
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/1tIEjer-gTrKwKipt7h65y3tN4NgUV09d/view"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:nicolas.saint@polytechnique.edu"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/nicolas-saint"
    - name: "github"
      url: "https://github.com/nicolassaint"
    # - name: "youtube"
    #   url: "https://www.youtube.com/c/AbdurRahmanKalim"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  # Add the API configuration
  api:
    endpoint: "https://api.olympia.bhub.cloud/generate"
    model: "llama3.1"
    temperature: 0.7
    stream: false

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true

# # Languages
# languages:
#   en:
#     weight: 1
#   fr:
#     weight: 2

